### ISSUE TITLE
Replace programming language icons

### ISSUE THREAD

**Issue by Calvin-rgb** [Snazzah/SublimeDiscordRP#49]
Used icons of programming languages are outdated in my opinion. I propose replacing them with Material, it will be much nicer to look aesthetically.

**Comment by Snazzah** [comment]
If you can send me some examples of icons that could look better than the current icons I can consider replacing them.

**Comment by dmsass** [comment]
What resolution should the icons be in? .png (What is the resolution? 512x512, 256x256, 64x54) ot .svg (vector)? @Snazzah

**Comment by Snazzah** [comment]
@dmsass 512x512

**Comment by Snazzah** [comment]
For reference, here are the current icons on the application.

![](https://get.snaz.in/7rr5orY.png)

I do agree that there lacks any consistency in style, I am open to any changes.

**Comment by botatooo** [comment]
### My suggestions

javascript: https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/512px-Unofficial_JavaScript_logo_2.svg.png
python: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/512px-Python-logo-notext.svg.png
rust: https://www.rust-lang.org/logos/rust-logo-512x512-blk.png
text: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Icon-txt.svg/512px-Icon-txt.svg.png
typescript: https://www.typescriptlang.org/icons/icon-512x512.png
unknown: lets use twemoji cause why not https://discord.com/assets/aef26397c9a6a3afee9c857c5e6f3317.svg
v: https://vlang.io/img/v-logo.png

sass because cool
sass: https://sass-lang.com/assets/img/logos/logo-b6e1ef6e.svg

**Comment by Snazzah** [comment]
@botatooo I replaced the V logo and Python logo

- The JS and TS logos you provided are a bit less consistent and might clip the text when using the `big_icon` setting.
- I'm considering replacing the `?` unknown logo with a blank file icon
- Rust is more or less the same as it is already, maybe add a color background like for JS and TS? (Same for Sass)

**Comment by botatooo** [comment]
i’ve found this for javascript, seems to fit with html and css’s design
![javascript](https://user-images.githubusercontent.com/63275405/89975587-2081a980-dc34-11ea-9c70-1a907ab4e817.png)

for typescript idk if we could fix that because that’s the logo they use in their marketing and stuffs

**Comment by FichteFoll** [comment]
From what I've seen, the first suggestion for the JS logo is indeed the most commonly used icon, but I see no benefit of using it over the better suited logo we currently have that allows it to be cut off a bit at the edges.

**Comment by TorchedSammy** [comment]
my fork has custom consistent icons that i think are really nice :l  
![](https://modeus.is-inside.me/Y15c76iS.png)  
if you want i can just zip em up and upload

**Comment by Snazzah** [comment]
@TorchedSammy Those icons look great! Could you upload them in a zip?

**Comment by TorchedSammy** [comment]
[Here they are](https://github.com/Snazzah/SublimeDiscordRP/files/5373931/langs.zip), ill probably make a separate repo for convenience

**Comment by Snazzah** [comment]
@TorchedSammy we could just make a folder in the repo to add the icons into for anyone that wants to use their own application ID

**Comment by TorchedSammy** [comment]
@Snazzah oh yea, feel free to and for any new icons ya can just ask me if you'd like

**Comment by Snazzah** [comment]
@TorchedSammy Also, speaking of your fork, would it be alright if you pushed some changes here? I've been meaning to get this package updated a bit anyways.

**Comment by TorchedSammy** [comment]
@Snazzah yep, I can open another PR with the changes in a while
